d = Dir.open(".")
head = "/* WARNING: autogenerated by extconf.rb */\n"
foot = "\nvoid Init_cshellsynth() {\n"
order = ["jackruby", "synths", "synth", "controllers", "controller", "mixer", "filters", "filter"]
order.each do |f|
  head += "void Init_" + f + "();\n"
  foot += "    Init_" + f + "();\n"
end
d.each do |f|
  if f.match ".*\.c\$"
    if((! order.member? f[0...-2]) && (f[0...-2] != "cshellsynth"))
      head += "void Init_" + f[0...-2] + "();\n"
      foot += "    Init_" + f[0...-2] + "();\n"
    end
  end
end

foot += "}\n"
if File.exist? "cshellsynth.c"
  File.delete("cshellsynth.c")
end
main = File.open("cshellsynth.c", "w")
main.puts head + foot

require 'mkmf'

$CFLAGS << " #{ENV["CFLAGS"]}"
$CFLAGS << " -Wall"

extension_name = 'cshellsynth'

dir_config(extension_name)

if(!have_library('jack', 'jack_client_open'))
  exit(0)
end

if(!have_library('cshellsynth', 'jclient_init'))
  exit(0)
end

create_makefile(extension_name)
