# extconf.rb
#
# Process this file with ruby to generate a Makefile.
#
# Copyright 2010 Evan Buswell
# 
# This file is part of Cshellsynth.
# 
# Cshellsynth is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
# 
# Cshellsynth is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Cshellsynth.  If not, see <http://www.gnu.org/licenses/>.

require 'mkmf'

$CFLAGS << " -Wall -Wextra"

d = Dir.open($curdir)
head = "/* WARNING: autogenerated by extconf.rb */\n#include <ruby.h>\n"
foot = "\nvoid Init_cshellsynth() {\n"
order = ["jackruby", "synths", "synth", "controllers", "controller", "mixer", "filters", "filter"]
order.each do |f|
  head += "void Init_" + f + "();\n"
  foot += "    Init_" + f + "();\n"
end
d.each do |f|
  if f.match ".*\.c\$"
    if((! order.member? f[0...-2]) && (f[0...-2] != "cshellsynth"))
      head += "void Init_" + f[0...-2] + "();\n"
      foot += "    Init_" + f[0...-2] + "();\n"
    end
  end
end

foot += "rb_require(\"cshellsynth/extra.rb\");
}\n"
if File.exist? "#$curdir/cshellsynth.c"
  File.delete("#$curdir/cshellsynth.c")
end
lib_main = File.open("#$curdir/cshellsynth.c", "w")
lib_main.puts head + foot
lib_main.close


$LIBPATH << "#$curdir/../src/.libs/"
$INCFLAGS << " " << "-I#$srcdir/../src".quote

if(!have_library('jack', 'jack_client_open'))
  exit(1);
end

$libs = append_library($libs, 'cshellsynth')
$distcleanfiles << "cshellsynth.c"

create_makefile('cshellsynth')
